<?php
/**
* @file
* A description of what your module does.
*/

require_once 'includes/idt.converter.inc';
require_once 'includes/idt.node.inc';
require_once 'includes/idt.ckeditor.inc';

/**
 * Implement hook_permission()
 */
function IndesignToDrupal_permission()
{
    return array(
        'Import from html'=>array(
            'title' => t('Indesign to drupal'),
            'description' => t('Importing html file from indsign to drupal database.'),
        ),
    );
}

/**
 * Implement hook_menu().
 */
function IndesignToDrupal_menu(){
    $item=array();
    $items['admin/config/content/htmlImport'] = array(
        'title' => 'Indesign to Drupal',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('IndesignToDrupal_setting_form'),
        'access arguments' =>array('Import from html'),
        'weight' => 1,
    );
    $items['admin/config/content/htmlImport/setting'] = array(
        'title' => 'settings',
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('IndesignToDrupal_setting_form'),
        'access arguments' =>array('Import from html'),
        'weight' => 6,
    );
    $items['admin/config/content/htmlImport/Which-fields'] = array(
        'title' => 'Fields',
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('IndesignToDrupal_setting_fields_form'),
        'access arguments' =>array('Import from html'),
        'weight' => 7,
    );
    $items['myImages/add'] = array(
        'title' => 'Add',
        'type' => MENU_CALLBACK,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('IndesignToDrupal_add_form'),
        'access arguments' =>array('Import from html'),
        'weight' => 7,
    );
    return $items;
}

function IndesignToDrupal_setting_form($form,&$form_state){

    $form=array();
    $fields=field_info_instances('node','article');
    if(variable_get('itd_title_active',0)) {
        $form['itd_title_classes'] = array(
            '#type' => 'textarea',
            '#title' => t('title'),
            '#default_value' => variable_get('itd_title_classes', ''),
        );
    }
    foreach($fields as $field){
        if(variable_get('itd_'.$field['field_name'].'_active',0)) {
            $form['itd_' . $field['field_name'] . '_classes'] = array(
                '#type' => 'textarea',
                '#title' => $field['label'],
                '#default_value' => variable_get('itd_' . $field['field_name'] . '_classes', ''),
            );
        }
    }
    return system_settings_form($form);
}

function IndesignToDrupal_setting_fields_form($form,&$form_state){
    $fields=field_info_instances('node','article');
    $form['itd-fields']=array(
        '#type' => 'fieldset',
        '#title' => t("Fields of Article"),
        '#collapsible' => False,
    );
    $form['itd-fields']['itd_title_active'] = array(
        '#title' => t('title'),
        '#type' => 'checkbox',
        '#default_value' => variable_get('itd_title_active',0),
    );
    foreach($fields as $field){
        $form['itd-fields']["itd_".$field['field_name']."_active"] = array(
            '#title' => $field['label'],
            '#type' => 'checkbox',
            '#description' => $field['field_name'],
            '#default_value' => variable_get("itd_".$field['field_name']."_active",0),
        );
    }
    return system_settings_form($form);
}

/**
 * Implements hook_field_extra_fields().
 */
function IndesignToDrupal_field_extra_fields()
{
    $extra['node']['article'] = array(
        'form' => array(
            'ITD_import_box' => array(
                'label' => t('Import from HTML'),
                'description' => t('Importing from Indesign html file'),
                'weight' => 0,
            ),
        ),
    );

    return $extra;
}
/**
 * Implements hook_form_alter().
 */
function IndesignToDrupal_form_alter(&$form, &$form_state, $form_id)
{

    if ($form_id == 'article_node_form') {
        $settings=array();
        $fields=field_info_instances('node','article');
        if (variable_get('itd_title_active', 0)) {
            $classes = variable_get('itd_title_classes', '');
            $classes = explode(",",$classes);
            $name = 'title';
            $type='textfield';
            $settings[]=array('name'=>$name,'class'=>$classes,'type'=>$type);
        }
        foreach($fields as $field) {
            if (variable_get('itd_' . $field['field_name'] . '_active', 0)) {
                $classes = variable_get('itd_' . $field['field_name'] . '_classes', '');
                $classes = explode(",",$classes);
                $name = $field['field_name'];
                $type=$field['widget']['type'];
                $settings[]=array('name'=>$name,'class'=>$classes,'type'=>$type);
            }
        }
        $form['ITD_import_box'] = array(
            '#type' => 'fieldset',
            '#title' => t('HTML Import'),
            '#collapsible' => True,
            '#collapsed' => False,
            '#group' => variable_get('domain_vertical_tab', 0) ? 'additional_settings' : '',
            '#attached' => array(
                'js'=> array(drupal_get_path('module', 'IndesignToDrupal') . '/js/itd.js' => array(
                    'type' => 'file',
                    ),
                ),
            ),
        );
        $form['ITD_import_box']['html_file'] = array(
            '#type' => 'markup',
            '#title' => t('input file'),
            '#markup' => '<input type="file" id="itd-file" style="display:block"/>',
        );
        $form['ITD_import_box']['file_display'] = array(
            '#type' => 'markup',
            '#title' => t('Imported file display:'),
            '#markup' => '<iframe id="itd-iframe" style="width: 50%;border: 1px solid #CCC;padding: 10px;margin: 10px 0;height: 400px;"></iframe>',
        );
        $form['ITD_import_box']['file_import_button'] = array(
            '#type' => 'markup',
            '#markup' => '<input type="button" id="convert-btn" value="Import" style="display: block;padding: 5px 15px;border: 1px solid;cursor: pointer;">',
        );
        $form['#attached']['js'][] = array(
            'data' => array('itd' => array('fields' => $settings)),
            'type' => 'setting',
        );
    }
    return $form;
}

/**
 * @param $form
 * @param $from_state
 */
function IndesignToDrupal_add_form($form, &$from_state){

    $form['picture_upload'] = array(
        '#type' => 'plupload',
        '#title' => t(''),
        '#size' => 50,
        '#description' => t(''),
        '#upload_validators' => array(
            'file_validate_extensions' => array('jpg jpeg gif png html      '),
            'my_custom_file_validator' => array('some validation criteria'),
        ),
    );
    $form['form_submit'] = array(
        '#type' => 'submit',
        '#value' =>'submit',
    );
    return $form;
}
function IndesignToDrupal_add_form_submit($form, &$form_state){



    // We can't use file_save_upload() because of
    // http://www.jacobsingh.name/content/tight-coupling-no-not
    // file_uri_to_object();
    $htmls = array();
    $images = array();

    //Separating Html files and images and storing them in the arrays.
    foreach ($form_state['values']['picture_upload'] as $uploaded_file) {
        if ($uploaded_file['status'] == 'done') {
            if(preg_match("/\\.html$/i",$uploaded_file['name'])){
              $htmls[$uploaded_file['name']]=$uploaded_file;
            }
            else{
                $images[$uploaded_file['name']]=$uploaded_file;
            }
        }
        else {
            // @todo: move this to element validate or something and clean up t().
            form_set_error('ITD', "Upload of {$uploaded_file['name']} failed");
        }
    }


    //Check if any html file has been uploaded successfully.
    //if no then print proper msg.
    if( count($htmls)){

        //Get settings
        $settings=array();
        $fields=field_info_instances('node','article');
        if (variable_get('itd_title_active', 0)) {
            $classes = variable_get('itd_title_classes', '');
            $classes = explode(",",$classes);
            $name = 'title';
            $type='textfield';
            $settings[]=array('name'=>$name,'class'=>$classes,'type'=>$type);
        }
        foreach($fields as $field) {
            if (variable_get('itd_' . $field['field_name'] . '_active', 0)) {
                $classes = variable_get('itd_' . $field['field_name'] . '_classes', '');
                $classes = explode(",",$classes);
                $name = $field['field_name'];
                $type=$field['widget']['type'];
                $settings[]=array('name'=>$name,'class'=>$classes,'type'=>$type);
            }
        }
        //Parse Html files
        $result=array();
        foreach ($htmls as $html_file){
            $result[]=_html_to_node($html_file, $images,$settings);
        }
    }
    else{
        // @todo: move this to element validate or something and clean up t().
        form_set_error('ITD', "Could not find any HTML file!");
    }

}
